(() => {
  const CATEGORY_EN = {
    'Accesibilidad':'Accessibility',
    'Construcción de conocimiento':'Knowledge building',
    'Diseño instruccional y planeación':'Instructional design and planning',
    'Evaluación y retroalimentación':'Assessment and feedback',
    'Investigación':'Research',
    'Metacognición y autorregulación':'Metacognition and self-regulation',
    'Producción audiovisual':'Audiovisual production',
    'Productividad y gestión':'Productivity and management',
    'Recursos sonoros':'Audio resources',
    'STEM y low-code':'STEM and low-code'
  };

  const EN = {
    'MagicSchool':{short:'Centralizes lesson planning, rubrics, and differentiation in an environment designed specifically for educators.',extended:'A teacher-focused platform that brings together lesson plans, rubrics, and differentiated resources. Its education-specific context reduces the need to build prompts from scratch.',cases:[['Objective-based lesson planning','A session with a specific success criterion.','Design a 45-minute collaborative activity on ecosystems for middle school, including an objective, closure, and assessment criteria.'],['Performance rubric','Assess an oral presentation or project.','Create a four-level rubric for a scientific presentation with criteria for content, evidence, and communication.'],['Differentiation by level','A group with different starting points.','Adapt this reading-comprehension activity for beginning learners without reducing cognitive challenge.']],pros:['Brings pedagogical functions into one environment.','Speeds up material creation with templates.','Supports differentiation with explicit criteria.'],cons:['Can produce generic results without local context.','Requires subject-matter validation.','Advanced features may require a subscription.']},
    'Eduaide':{short:'Designs instructional sequences and diagnostic assessments adapted to each class context.',extended:'An instructional-design assistant for producing activities, diagnostics, and active-learning dynamics across opening, development, assessment, and closure.',cases:[['Entry diagnostic','Start of a unit or new course.','Design five diagnostic questions about renewable energy to identify prior knowledge in high school.'],['Active learning','Collaborative in-person session.','Generate a challenge-based activity to teach proportional reasoning in middle school teams of four.'],['Differentiated activity','Different mastery levels.','Adapt this algebra activity into basic, intermediate, and advanced versions with the same learning objective.']],pros:['Aligns activities with instructional moments.','Generates actionable diagnostics.','Produces differentiated versions quickly.'],cons:['Less flexible for nonformal education.','Export and collaboration may be limited.','Needs teacher context to avoid generic results.']},
    'Turnitin':{short:'Detects textual similarity and structures written feedback for academic work.',extended:'A similarity-checking and formative-feedback system that supports review of text matches, draft development, argumentation, and source use.',cases:[['Text originality','Essay or research paper.','Analyze textual similarities in this essay and identify sections that need citation or paraphrasing review.'],['Written argumentation','Academic writing in progress.','Identify weaknesses in the argument and suggest how to improve the link between evidence and conclusions.'],['Draft tracking','Writing developed in stages.','Compare this draft with the previous version and identify improvements and remaining issues.']],pros:['Integrates with institutional LMS platforms.','Supports tracking of the writing process.','Useful for academic integrity workflows.'],cons:['Can generate false positives.','A similarity percentage alone does not determine plagiarism.','Rubric setup requires time.']},
    'Gradescope':{short:'Groups student responses and speeds consistent grading at scale.',extended:'An assisted-assessment platform that clusters similar responses, supports consistency across graders, and reveals recurring error patterns.',cases:[['Batch grading','Short responses in large groups.','Group open responses by conceptual similarity and suggest a baseline score for each cluster.'],['Error patterns','Misunderstood concepts.','Identify the three most common errors in this calculus exam and describe each conceptual pattern.'],['Shared grading criteria','Multiple graders.','Define shared scoring criteria for this question and create a consistent grading guide.']],pros:['Reduces inconsistency across graders.','Turns assessment into diagnostic information.','Works with exams, submissions, and code.'],cons:['Initial setup takes time.','Accuracy drops with highly variable responses.','Best suited to structured assessments.']},
    'Lumen5':{short:'Turns text or scripts into short videos for topic onboarding and module summaries.',extended:'Transforms text into audiovisual capsules using images, music, and preset transitions. Useful for welcomes, summaries, and introductory learning materials.',cases:[['Course onboarding','First contact with a module.','Turn this course summary into a 90-second welcome video with a motivating tone.'],['Summary capsule','End of a thematic unit.','Create a two-minute capsule summarizing five key concepts about climate change.'],['Flipped pre-class resource','Material viewed before class.','Turn this photosynthesis script into a short explanatory video for students to watch before class.']],pros:['Reduces time needed for introductory video production.','Does not require advanced recording or editing.','Templates help standardize educational materials.'],cons:['Automatically selected visuals may be inaccurate.','Visual styles can become repetitive.','Deeper customization may require payment.']},
    'Pictory':{short:'Transforms long articles and readings into review videos for self-directed learning.',extended:'Converts long documents into short videos by selecting key excerpts and automatically segmenting them into scenes.',cases:[['Reading summary','Academic article to video.','Turn this educational article into a three-minute video summary highlighting the main findings.'],['Review capsule','Independent preparation.','Create a 90-second review capsule on the causes of World War II.'],['Pre-class resource','Activation before class.','Create an introductory video about solar energy from this two-page document.']],pros:['Processes long documents.','Speeds up review-resource creation.','Accepts user-provided materials.'],cons:['May omit dense or nuanced ideas.','Narrative control is limited.','Works best with well-structured source text.']},
    'Runway':{short:'Creates and edits AI video for educational simulations and more complex visual narratives.',extended:'A generative audiovisual suite for creating scenes, editing video with natural-language commands, and building visual narratives with greater creative control.',cases:[['Visual simulation','Historical, scientific, or social context.','Generate a visual simulation of a sustainable city in 2050 with electric mobility and green spaces.'],['Audiovisual narrative','Resource with a narrative arc.','Create a 30-second sequence showing the urban impact of the Industrial Revolution.'],['Teacher post-production','Improve recorded video.','Remove the background from this video, improve lighting, and add Spanish subtitles.']],pros:['Natural-language video editing.','More control than template-based tools.','Combines generation and post-production.'],cons:['Higher learning curve.','High-quality output can require more resources.','Advanced credits can be consumed quickly.']},
    'Suno':{short:'Creates thematic songs to reinforce curriculum through musical memory.',extended:'Generates music and lyrics from a topic, tone, and style. Useful for memorization, session openings, and playful learning experiences.',cases:[['Concept anchoring','Content that is hard to remember.','Compose a two-minute pop song about the water cycle including evaporation, condensation, and precipitation.'],['Session opener','Initial activation.','Generate an energetic song for a teacher workshop on educational innovation.'],['Mnemonic resource','Formula retention.','Create a rap to help middle school students remember area formulas for geometric figures.']],pros:['Creates songs without requiring music skills.','Can support retention through musical memory.','Adapts style to age and context.'],cons:['Lyrics need conceptual validation.','Technical musical control is limited.','Free credits can restrict use.']},
    'Speechify':{short:'Turns documents and academic readings into audio for mobile and inclusive study.',extended:'Converts documents, PDFs, and web pages into audio with adjustable voice and speed, supporting reading accessibility and multimodal review.',cases:[['Accessible reading','Support for dyslexia or low reading fluency.','Convert this academic article into narration with moderate speed and pauses between paragraphs.'],['Mobile study','Review while commuting.','Turn this history summary into audio for a 20-minute screen-free review.'],['Audio review','Teacher review without a screen.','Read this instructional draft aloud so I can detect unclear sentences or overly long paragraphs.']],pros:['Works with multiple formats.','Playback speed is adjustable.','Supports inclusion without redesigning source materials.'],cons:['Basic voices may sound less natural.','More natural voices may require payment.','Depends on learners benefiting from auditory study.']},
    'Immersive Reader':{short:'Visually adapts academic text for guided reading, translation, and inclusive access.',extended:'Microsoft reading-support tool with line focus, syllable separation, read-aloud, grammar highlighting, and translation options.',cases:[['Guided reading','Complex classroom text.','Enable line focus and syllable separation for this high-school biology text.'],['Bilingual support','Reading in a second language.','Translate this article into Spanish while preserving reading layout and grammar highlighting.'],['Visual focus','Difficulty sustaining attention.','Configure wider spacing, line focus, and a clear font to reduce visual distraction.']],pros:['Available across Microsoft 365.','Combines several accessibility supports.','Does not alter the original document.'],cons:['Customization follows preset options.','Depends on the Microsoft ecosystem.','Does not replace specialized intervention.']},
    'Semantic Scholar':{short:'Finds scientific articles and maps connections among studies through citation analysis.',extended:'An academic search engine that reveals relationships among studies, authors, citations, and topics to identify evidence, research lines, and gaps.',cases:[['Recent evidence','Updated theoretical framework.','Find studies published after 2021 on the effectiveness of hybrid learning in upper-secondary education.'],['Academic influence','Foundational studies.','Show the five most-cited articles on AI in higher education and their relationships.'],['Topic network','Literature review.','Starting from this gamification article, identify related studies on motivation and student persistence.']],pros:['Uses citations to signal relevance.','Helps locate open PDFs.','Supports detection of gaps and trends.'],cons:['Spanish-language coverage can be smaller.','Recent indexing may take time.','Less directly useful for instructional design.']},
    'Notion AI':{short:'Summarizes meetings, organizes educational projects, and builds collaborative knowledge repositories.',extended:'An assistant inside Notion for summarizing notes, structuring projects, and organizing information in collaborative databases.',cases:[['Academic synthesis','Faculty meeting.','Summarize these notes into concrete agreements, owners, and key dates for the next academic cycle.'],['Educational project','Institutional coordination.','Organize this curriculum redesign into phases, owners, tasks, and measurable progress criteria.'],['Academic repository','Course materials.','Create a graduate-course repository structure organized by module, resource, and progress.']],pros:['Combines writing, databases, and collaboration.','Generates structures from scratch.','History supports editorial tracking.'],cons:['Moderate initial learning curve.','Advanced AI may require payment.','Can become cluttered without clear architecture.']},
    'Replit':{short:'Builds STEM prototypes and educational applications with AI-assisted programming in the browser.',extended:'An online environment for creating, running, and publishing software from a browser with AI assistance, supporting prototypes, simulations, and collaborative STEM projects.',cases:[['STEM prototype','Functional solution to a problem.','Create a simple web app to calculate daily carbon footprint and display reduction recommendations.'],['Basic simulator','Interactive mathematical relationship.','Build a visual linear-motion simulator with controls for speed, time, and distance.'],['Collaborative project','Code and documentation online.','Organize this project into HTML, CSS, and JavaScript files with comments for beginning students.']],pros:['Avoids local installation.','Builds, tests, and publishes in one environment.','AI accelerates debugging and prototyping.'],cons:['Can hide foundational concepts.','Complex projects still need architecture.','Free plans may limit resources.']},
    'GitHub Copilot':{short:'Supports writing, explaining, and reviewing code in advanced STEM projects.',extended:'A programming assistant integrated into editors that suggests code, explains functions, supports debugging, and proposes tests.',cases:[['Code explanation','Understand before modifying.','Explain this Python code line by line and identify the concepts an intermediate student should master.'],['Guided debugging','Execution errors.','Identify the error in this function, explain the cause, and propose a minimal commented fix.'],['Software testing','Solution quality.','Generate unit tests for this function and explain which edge case each test covers.']],pros:['Speeds coding and review.','Explains snippets and errors.','Supports testing and documentation.'],cons:['Can generate code students do not understand.','Requires security oversight.','Loses educational value if it simply completes tasks.']},
    'NotebookLM':{short:'Connects user-provided sources for contextual study and guided knowledge building.',extended:'A study assistant that works from uploaded sources to generate guides, maps, summaries, and questions grounded in the user’s own materials.',cases:[['Guided reading','Core unit documents.','From these readings, create a study guide with key concepts, questions, and connections among authors.'],['Comparative synthesis','Compare sources.','Compare these three documents and identify agreements, differences, and conceptual tensions for discussion.'],['Academic seminar','Source-grounded conversation.','Generate ten seminar questions using only these sources, ordered from comprehension to critical analysis.']],pros:['Works from user-provided materials.','Turns documents into guides and connections.','Supports dialogue grounded in course sources.'],cons:['Depends on careful source selection.','May simplify conceptual tensions.','Does not replace critical reading.']},
    'ChatGPT':{short:'Structures activities, explanations, and adaptable materials for many educational contexts.',extended:'A flexible conversational assistant for generating materials, ideas, feedback, and teaching support across educational levels.',cases:[['Rapid lesson planning','Weekly class design.','Design a 50-minute lesson on fractions for elementary students with opening, development, and closure.'],['Layered explanation','Complex content.','Explain photosynthesis at three levels: elementary, middle school, and high school.'],['Feedback','Review written work.','Provide formative feedback on this essay, highlighting strengths and opportunities for improvement.']],pros:['Versatile across many tasks.','Reduces design time.','Supports contextual adaptation.'],cons:['Can fabricate information.','Depends on clear prompts.','Requires teacher validation.']},
    'Claude':{short:'Analyzes long documents and synthesizes complex ideas with strong contextual coherence.',extended:'An assistant oriented to reading, analysis, and organization of extended information for academic synthesis and document-based work.',cases:[['Document analysis','Long readings.','Summarize these three articles and identify their main agreements and conceptual tensions.'],['Editorial design','Repository or catalog.','Propose an editorial structure for organizing educational tools by pedagogical function.'],['Academic synthesis','Course research.','Turn this theoretical framework into a one-page study synthesis.']],pros:['Handles broad context.','Strong document coherence.','Useful for complex synthesis.'],cons:['May oversimplify.','Features depend on plan.','Does not replace critical reading.']},
    'Perplexity':{short:'Finds recent information with integrated citations for rapid academic exploration.',extended:'A conversational search engine focused on locating and synthesizing current information with visible references.',cases:[['Recent search','Emerging topic.','Find recent studies on hybrid learning in higher education and summarize the findings.'],['Initial exploration','Start of research.','Identify current trends in AI-mediated formative assessment.'],['Quick sources','Teacher preparation.','Find introductory open resources on digital literacy with references.']],pros:['Combines search and synthesis.','Shows references quickly.','Useful for early exploration.'],cons:['Quality depends on web sources.','Can summarize without depth.','Does not replace formal academic review.']},
    'Canva Magic Design':{short:'Creates educational presentations and visual resources with AI-assisted templates.',extended:'A visual tool for producing slides, infographics, and quick instructional materials with generative support.',cases:[['Visual presentation','Expository class.','Generate a visual presentation about recycling for middle school with simple icons and examples.'],['Infographic','Visual summary.','Design an educational infographic about the water cycle using accessible language.'],['Social content','Institutional outreach.','Create a social-media carousel about effective study habits.']],pros:['Highly accessible for educators.','Reduces visual-design time.','Large resource library.'],cons:['Templates can feel repetitive.','Premium features are limited by plan.','Still requires basic visual judgment.']},
    'Gamma':{short:'Turns outlines and ideas into navigable presentations and visual documents.',extended:'A presentation and interactive-document generator with automatic structure and adaptable design.',cases:[['Visual class','Quick presentation.','Turn this outline on digital citizenship into a clear, concise visual presentation.'],['Executive report','Institutional synthesis.','Generate a visual report with results from a school diagnostic assessment.'],['Interactive guide','Self-paced material.','Create a navigable visual guide on critical thinking for high school.']],pros:['Consistent automated design.','Reduces layout time.','Easy export options.'],cons:['Visual control is limited.','May oversimplify structure.','Depends on clear prompts.']},
    'Leonardo AI':{short:'Generates educational images and visual scenes tailored to learning content.',extended:'A visual-generation tool for creating illustrations, scenes, and customized graphic resources.',cases:[['Concept illustration','Abstract topic.','Generate an educational food-chain illustration with a clear style and soft colors.'],['Historical scene','Visual contextualization.','Create a visual scene of a Mesopotamian city for instructional use.'],['Educational character','Visual narrative.','Design a guide character for elementary natural-science content.']],pros:['High visual control.','Useful for custom resources.','Supports varied styles.'],cons:['Requires precise prompts.','Can generate visual errors.','Moderate learning curve.']},
    'ElevenLabs':{short:'Produces educational narration with natural synthetic voices and expressive control.',extended:'A voice-synthesis platform for creating audio guides, narration, and educational listening resources.',cases:[['Audio lesson','Asynchronous content.','Generate a clear narration on plate tectonics with a teacher-like tone and natural pauses.'],['Audio accessibility','Inclusive material.','Convert this document to audio with a warm voice and moderate speed.'],['Educational podcast','Short-form outreach.','Create a podcast-style narration about renewable energy for middle school.']],pros:['Very natural voices.','Improves audio accessibility.','Supports different tones and styles.'],cons:['Advanced features are paid.','Ethical use requires oversight.','Advanced editing takes time.']},
    'Elicit':{short:'Organizes academic evidence and compares findings across scientific studies.',extended:'A research-review assistant that helps locate, compare, and synthesize scientific studies.',cases:[['Study comparison','Literature review.','Compare these articles on active learning, identifying methods and key findings.'],['Evidence map','Topic exploration.','Organize recent evidence on generative AI in higher education.'],['Rapid synthesis','Academic preparation.','Summarize contributions and limitations of these five studies on digital assessment.']],pros:['Supports academic review.','Synthesizes findings quickly.','Helps compare evidence.'],cons:['Does not replace full-text reading.','May omit nuance.','Most useful with English-language sources.']},
    'PhET':{short:'Explores scientific phenomena through interactive simulations for experimental learning.',extended:'A repository of STEM simulations that lets learners manipulate variables and visualize complex scientific phenomena.',cases:[['Scientific simulation','Experimental class.','Explore changes in gas temperature and volume using an interactive simulation.'],['Visual learning','Abstract concepts.','Use an electric-circuits simulation to identify current flow and resistance.'],['Independent work','Individual activity.','Design an exploration guide for a gravity simulation.']],pros:['Highly visual and accessible.','Supports experimental learning.','Works across multiple levels.'],cons:['Topic coverage is limited.','Requires teacher mediation.','Does not replace a real laboratory.']},
    'Gemini':{short:'Connects text, images, and web search for multimodal exploration of educational content.',extended:'Google’s multimodal assistant for synthesis, visual exploration, and combined analysis across formats.',cases:[['Multimodal exploration','Text and image together.','Explain this biology diagram and summarize the key concepts in accessible language.'],['Concept comparison','Rapid synthesis.','Compare hybrid learning and flipped learning with applied examples.'],['Visual analysis','Interpret a resource.','Describe this infographic and identify its main concepts for a lesson.']],pros:['Integrates multiple formats.','Useful for rapid exploration.','Connects search and synthesis.'],cons:['Can oversimplify.','Results vary by context.','Requires teacher validation.']},
    'Hacedor de metáforas (GPT)':{name:'Metaphor Maker (GPT)',short:'Turns abstract concepts into understandable mental images through pedagogical analogies.',extended:'A specialized GPT for translating complex ideas into instructional metaphors and intuitive connections, helping learners grasp scientific, philosophical, or technical concepts through memorable mental models.',cases:[['Complex concept','Abstract or technical topic.','Explain entropy using an everyday metaphor for high-school students.'],['Instructional explanation','Teaching and training.','Create a metaphor to explain collaborative leadership to a group of educators.'],['Intuitive understanding','Deep learning.','Explain blockchain to a nontechnical audience using simple, visual analogies.']],pros:['Supports intuitive understanding.','Creates memorable connections.','Adapts metaphors to different audiences.'],cons:['Metaphors simplify details.','Can create subjective interpretations.','Does not replace formal technical rigor.']},
    'ChatPDF':{short:'Lets users converse with academic documents to locate ideas and understand long readings.',extended:'A conversational tool for analyzing PDFs, answering questions, and summarizing educational or scientific documents.',cases:[['Guided reading','Long academic article.','Summarize this PDF, identifying objectives, methodology, and main findings.'],['Targeted search','Locate specific information.','In which section does the document explain self-regulated learning?'],['Class preparation','Extract key ideas.','Generate five discussion questions based on this article.']],pros:['Speeds document review.','Makes PDFs easier to explore.','Useful for quick synthesis.'],cons:['Depends on PDF quality.','May omit important nuance.','Does not replace full reading.']},
    'Wolfram Alpha':{short:'Solves mathematical and scientific problems with step-by-step processes and representations.',extended:'A computational engine for mathematics, physics, and scientific analysis with visualizations and structured problem solving.',cases:[['Mathematical solution','Algebra exercise.','Solve this quadratic equation showing each step and a graph.'],['Scientific visualization','Understanding functions.','Graph this trigonometric function and explain amplitude and period.'],['STEM analysis','Scientific data.','Calculate average speed and present the results in a simple table.']],pros:['Shows step-by-step processes.','Highly useful for STEM.','Generates mathematical visualizations.'],cons:['Moderate learning curve.','Less useful outside STEM.','Requires precise questions.']},
    'ExplainPaper':{short:'Clarifies complex passages from scientific papers with contextual explanations.',extended:'An academic-reading tool that simplifies technical paragraphs and specialized concepts within research papers.',cases:[['Scientific reading','Complex paper.','Explain this paragraph on neural networks in accessible language for beginning graduate students.'],['Method understanding','Technical section.','Summarize this experimental methodology, highlighting variables and main objectives.'],['Research support','First disciplinary approach.','Clarify the statistical concepts mentioned in this education article.']],pros:['Reduces barriers to scientific reading.','Explains technical terms in context.','Useful for student researchers.'],cons:['Can oversimplify.','Most useful in English.','Does not replace disciplinary reading.']},
    'Firefly':{short:'Generates images and visual compositions for instructional materials and educational communication.',extended:'Adobe’s generative visual tool for creating images inside design workflows used for educational content.',cases:[['Instructional illustration','Visual support for content.','Generate an educational illustration of marine ecosystems with a clear visual style.'],['Institutional design','School communication.','Create a visual banner for a school reading campaign.'],['Visual resource','Educational presentation.','Design a visual scene about renewable energy for academic slides.']],pros:['Integrates with Adobe tools.','Produces visually consistent results.','Useful for rapid educational resources.'],cons:['Advanced functions require a subscription.','Depends on clear prompts.','Less technical control than manual design.']},
    'DALL·E':{short:'Produces conceptual images for instructional visual support and explanation.',extended:'A natural-language image generator useful for representing abstract concepts and creating customized visual learning materials.',cases:[['Abstract concept','Hard-to-visualize topic.','Generate an educational solar-system visualization in a simple infographic style.'],['Visual narrative','Storytelling support.','Create a futuristic scene to explain sustainable cities in class.'],['Instructional material','Visual content support.','Design an educational food-chain illustration for elementary students.']],pros:['Turns ideas into images quickly.','Supports visual learning.','Enables customized resources.'],cons:['Can generate conceptual errors.','Results vary with prompts.','Requires teacher visual review.']},
    'Canva':{short:'Designs presentations, infographics, and visual materials for accessible educational communication.',extended:'A widely used visual platform for rapidly creating educational resources through templates and simplified design tools.',cases:[['Visual presentation','Expository class.','Design a biodiversity presentation with clear icons and a simple visual structure.'],['Educational infographic','Concept summary.','Create an infographic about effective study habits for high school.'],['School communication','Institutional outreach.','Generate a visual poster for a school science fair.']],pros:['Very accessible for educators.','Reduces design time.','Large visual library.'],cons:['Templates can become repetitive.','Premium features are limited.','Can prioritize aesthetics over content.']},
    'Soundraw':{short:'Composes adaptable background music for videos, capsules, and educational multimedia.',extended:'A music generator for creating adjustable instrumental tracks to accompany audiovisual content.',cases:[['Background music','Educational video.','Generate soft instrumental music for an educational astronomy capsule.'],['Sound narrative','Audiovisual resource.','Create an energetic track to introduce an educational-innovation module.'],['Educational podcast','Audio production.','Compose a subtle music bed for a podcast on contemporary history.']],pros:['Generates music quickly.','Lets users adjust duration and style.','Useful for multimedia production.'],cons:['Less advanced compositional control.','Styles may feel similar.','Advanced features require payment.']},
    'Cogni':{short:'Supports reflection on learning and study habits through guided analysis.',extended:'A tool focused on metacognition and self-regulation to identify learning patterns, habits, and study strategies.',cases:[['Academic reflection','Process tracking.','Generate reflection questions so students can evaluate how they studied this week.'],['Study habits','Self-regulation.','Identify distraction patterns and suggest simple adjustments to an academic routine.'],['Cognitive tracking','Learning awareness.','Design a self-assessment template to monitor understanding and concentration.']],pros:['Promotes awareness of learning.','Supports study habits.','Complements tutoring and follow-up.'],cons:['Depends on honest reflection.','Results benefit from guidance.','Does not replace pedagogical intervention.']},
    'Story Creator Visual':{short:'Turns ideas into short visual narratives for educational communication and emotional connection.',extended:'A GPT for visual storytelling that transforms concepts, messages, or topics into brief stories with coherent visual direction, helping contextualize educational and institutional content.',cases:[['Educational narrative','Contextualize an abstract concept through a short story.','Create a simple story about teamwork for middle-school students.'],['Presentation opening','Open a talk or lesson with emotional impact.','Generate a short story about educational innovation to open a conference.'],['Visual communication','Connect institutional ideas with a specific audience.','Create a visual narrative about resilience for a university campaign.']],pros:['Turns concepts into memorable narrative experiences.','Combines narrative and visual direction.','Supports emotional connection with educational content.'],cons:['Some stories require contextual adaptation.','Quality depends on a clear initial objective.','Does not replace a full narrative or pedagogical strategy.']},
    'Rutas de decisión de vida':{name:'Life Decision Paths',short:'Simulates personal and professional decisions to explore consequences and strategic thinking.',extended:'An interactive GPT based on narrative scenarios where users make decisions about career, finances, entrepreneurship, and lifestyle, generating simulated consequences that support reflection and planning.',cases:[['Life project','Explore personal and professional pathways.','I want to start my career after university.'],['Financial decisions','Evaluate possible risks and benefits.','I have $10,000 saved. What should I do?'],['Personal planning','Analyze major contextual changes.','I want to move to another country and work remotely.']],pros:['Supports learning through simulation.','Develops strategic and future-oriented thinking.','Generates personalized narrative experiences.'],cons:['Does not replace professional advice.','Consequences are simulated and approximate.','Needs sufficient context for coherence.']},
    'Ejercicios Math IA':{name:'Math AI Exercises',short:'Generates mathematics practice by level with explanations and instructional reinforcement.',extended:'An educational GPT for creating math exercises, explanations, and activities adjusted to grade level and difficulty, supporting practice, differentiation, and guided reinforcement.',cases:[['School practice','Create level-appropriate exercises.','Generate 10 fraction exercises for fifth grade with answers.'],['Simple explanation','Simplify complex math concepts.','Explain linear equations in simple terms for middle-school students.'],['Academic reinforcement','Support learners with specific difficulties.','Create basic division exercises for students who need extra support.']],pros:['Adapts exercises by educational level.','Generates clear, progressive explanations.','Reduces teacher preparation time.'],cons:['Requires specific instructions.','Needs contextual pedagogical validation.','Does not automatically create final files.']},
    'Feedback: I like, I wish, What if':{short:'Structures empathetic and constructive feedback for projects, classes, and educational proposals.',extended:'A GPT based on the “I like, I wish, What if” framework for formative feedback on activities, lesson plans, and educational projects.',cases:[['Instructional feedback','Review plans and learning activities.','Analyze this science lesson plan using I like, I wish, What if.'],['Educational innovation','Improve early pedagogical proposals.','Give me feedback on this project-based learning activity for elementary students.'],['Collaborative review','Support peer review among educators.','Act as a teaching colleague and review this instructional sequence.']],pros:['Supports empathetic formative feedback.','Structures continuous-improvement conversations.','Facilitates collaborative review.'],cons:['Depends on sufficiently clear input.','Does not replace specialized evaluation.','May require additional educational context.']},
    'Drive On Your Course':{short:'Designs active-learning experiences through simulations, challenges, and gamified dynamics.',extended:'A GPT for interactive learning experiences using gamification, role-play, simulations, and active methodologies for educational and professional practice.',cases:[['Career exploration','Explore interests and possible pathways.','Design a gamified mission to help me discover which career might fit me.'],['Professional role-play','Practice workplace and communication skills.','Run a role-play interview for a marketing internship.'],['Academic Boss Fight','Review content through progressive challenges.','Create an algebra Boss Fight with progressively harder questions for middle school.']],pros:['Increases participation through active learning.','Combines simulation, narrative, and contextual practice.','Adapts dynamics to objectives and learner level.'],cons:['Does not replace specialized career guidance.','Requires human facilitation and implementation.','Quality depends on clearly defined objectives.']},
    'Napkin AI':{short:'Turns text into diagrams, mind maps, infographics, and clear visuals for communicating complex ideas.',extended:'An AI tool that converts written or pasted text into professional visuals such as diagrams, mind maps, flows, schemes, and infographics without requiring advanced design skills.',cases:[['Graphic organizer','Turn theory into visual support.','Transform this text about active learning into a clear mind map for university educators.'],['Process diagram','Explain an instructional sequence or methodology.','Turn this instructional-strategy description into a flowchart with clear, concise steps.'],['Class infographic','Communicate complex ideas visually.','Create an educational infographic from this text about generative AI and responsible use.']],pros:['Converts text into visuals quickly.','Helps explain complex ideas.','Does not require advanced design skills.'],cons:['Can oversimplify complex conceptual relationships.','Visual accuracy and hierarchy require review.','Available features can vary by plan.']},
    'Consensus':{short:'Finds and synthesizes peer-reviewed scientific evidence to answer research questions.',extended:'An AI-powered academic search engine that consults scientific literature and synthesizes findings to help educators, students, and researchers compare evidence and identify scientific consensus.',cases:[['Updated teaching research','Find evidence on educational innovation.','Do chatbots improve learning outcomes in university students?'],['Educational evidence synthesis','Compare supportive and contradictory studies.','What effects does gamification have on academic performance?'],['Scientific consensus indicator','See whether evidence supports or challenges a hypothesis.','Does artificial intelligence help students learn faster?']],pros:['Consults peer-reviewed scientific evidence.','Shows a visual indication of consensus.','Supports academic responses with references.'],cons:['Works best with questions in English.','Not ideal for basic facts or simple data lookups.','Free use may be limited.']},
    'Typecast':{short:'Turns text into expressive, natural AI voices for narration, dialogue, and educational audio.',extended:'An AI voice-generation platform that transforms text into synthetic speech with selectable voices, emotion, pacing, and delivery styles for audio lessons, dialogue, explanatory video, and multimedia learning.',cases:[['Short audio lesson','Turn a written explanation into an audio resource.','Photosynthesis is the process by which plants transform light energy into chemical energy…'],['Listening-comprehension dialogue','Create multi-voice conversations for language-learning listening practice.','Create a short dialogue between a customer and a waiter ordering breakfast at a restaurant. Use everyday English appropriate for A2 learners.'],['Narration and characters','Give voice to characters, perspectives, or situations.','Create a conversation between a scientist and a student explaining the greenhouse effect from their different perspectives.']],pros:['Produces narration without recording equipment.','Adapts voice, emotion, and style to the purpose.','Speeds creation of audio and multimedia learning resources.'],cons:['Naturalness and expressiveness vary by voice and language.','Voices and generation limits depend on the plan.','Synthetic voices require transparency and responsible-use criteria.']}
  };

  const STATIC_EN = {
    title:'AI Tools for Education Catalog',
    subtitle:'A curated editorial repository for identifying tools by pedagogical use, not by technology trend.',
    credit:'Curated by Olaf Román ↗',
    tools:'Tools', categories:'Categories', cases:'Prompt-based cases', search:'Search...',
    guide:'Guide for purposeful pedagogical use', guideLeadTitle:'AI tools for the classroom',
    guideLead:'A companion to the catalog for making clearer decisions about which tool to choose, when to use it, and how to integrate it into instructional design.',
    guideSections:[
      ['1. The problem is not the tool','Most educators do not have an access problem but a judgment problem: too many options and too little clarity about what each one is good for.'],
      ['2. Pedagogical flow','Each tool is easier to understand when connected to a moment in learning: opening, development, closure, feedback, or independent review.'],
      ['3. Four selection criteria',''],
      ['4. When not to use AI','Avoid it when the learner’s process is itself essential to learning or when there is not enough time to validate the output.'],
      ['5. How to read the catalog','Each card follows the same structure: short description, extended description, use cases, advantages, and limitations for easier editorial comparison.'],
      ['6. Gradual integration','Sustainable adoption starts with focused support before redesigning entire processes around a tool.'],
      ['7. Teacher validation','AI produces plausible drafts; professional judgment determines what is accurate, relevant, and appropriate for each educational context.']
    ],
    criteria:['What does it solve that you cannot do as well without it?','At what point in the design does it enter?','What do you validate before taking it into the classroom?','Does it integrate with or replace your current practice?'],
    footer:'AI Tools for Education Catalog · Curation and editorial design:',
    go:'Go to tool ↗', fiche:'▶ Pedagogical profile', useCases:'Use cases', advantages:'✔ Advantages', limitations:'✘ Limitations'
  };

  const original = new Map();
  const categoryOriginal = new Map();
  let currentLang = localStorage.getItem('catalog-language') === 'en-US' ? 'en-US' : 'es-419';

  function snapshot(){
    document.querySelectorAll('.card').forEach(card => {
      const name = card.querySelector('h2')?.textContent?.trim();
      if(!name || original.has(name)) return;
      original.set(name, {
        h2:name,
        category:card.querySelector('.tag')?.textContent?.trim() || '',
        short:card.querySelector('.short')?.textContent || '',
        extended:card.querySelector('.extended')?.textContent || '',
        summary:card.querySelector('details > summary')?.textContent || '',
        cases:[...card.querySelectorAll('.case')].map(c=>({title:c.querySelector('b')?.textContent||'',desc:c.querySelector('span')?.textContent||'',prompt:c.querySelector('.prompt')?.textContent||''})),
        pros:[...card.querySelectorAll('.box:not(.limit) li')].map(x=>x.textContent),
        cons:[...card.querySelectorAll('.box.limit li')].map(x=>x.textContent)
      });
    });
    document.querySelectorAll('#categoryMenu details').forEach(d=>{
      const s=d.querySelector(':scope > summary'); if(s) categoryOriginal.set(d,s.innerHTML);
    });
  }

  function addStyles(){
    if(document.getElementById('catalog-language-style')) return;
    const style=document.createElement('style'); style.id='catalog-language-style';
    style.textContent=`.catalog-language-switch{position:absolute;top:18px;right:6vw;z-index:5;display:flex;align-items:center;gap:8px;padding:7px 9px;border-radius:999px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.24);backdrop-filter:blur(8px)}.catalog-language-switch label{font-size:.78rem;font-weight:750;color:#fff}.catalog-language-switch select{appearance:none;border:1px solid rgba(255,255,255,.3);background:rgba(255,255,255,.96);color:#17324d;border-radius:999px;padding:7px 28px 7px 10px;font:inherit;font-size:.8rem;font-weight:700;cursor:pointer}.catalog-language-switch:after{content:'⌄';position:absolute;right:17px;color:#2563eb;pointer-events:none}@media(max-width:760px){.catalog-language-switch{position:relative;top:auto;right:auto;width:max-content;margin:0 0 20px 6vw}.catalog-language-switch label{display:none}}`;
    document.head.appendChild(style);
    const header=document.querySelector('header'); if(header && getComputedStyle(header).position==='static') header.style.position='relative';
  }

  function addSelector(){
    if(document.getElementById('catalogLanguage')) return;
    addStyles();
    const wrap=document.createElement('div'); wrap.className='catalog-language-switch';
    wrap.innerHTML=`<label for="catalogLanguage">Idioma / Language</label><select id="catalogLanguage" aria-label="Idioma / Language"><option value="es-419">Español Latinoamericano</option><option value="en-US">English (US)</option></select>`;
    const header=document.querySelector('header'); header?.prepend(wrap);
    const sel=wrap.querySelector('select'); sel.value=currentLang;
    sel.addEventListener('change',()=>{currentLang=sel.value;localStorage.setItem('catalog-language',currentLang);applyLanguage();});
  }

  function sortAlphabetically(){
    const grid=document.getElementById('grid');
    if(grid){[...grid.querySelectorAll('.card')].sort((a,b)=>(a.querySelector('h2')?.textContent||'').localeCompare((b.querySelector('h2')?.textContent||''), currentLang==='en-US'?'en-US':'es-MX',{sensitivity:'base'})).forEach(x=>grid.appendChild(x));}
    document.querySelectorAll('#categoryMenu .tool-chips').forEach(box=>{[...box.querySelectorAll('.chip')].sort((a,b)=>a.textContent.localeCompare(b.textContent,currentLang==='en-US'?'en-US':'es-MX',{sensitivity:'base'})).forEach(x=>box.appendChild(x));});
  }

  function translateCard(card,toEnglish){
    const spanishName=[...original.keys()].find(n=>original.get(n) && (card.dataset.originalName===n || original.get(n).h2===card.querySelector('h2')?.textContent)) || card.dataset.originalName || card.querySelector('h2')?.textContent?.trim();
    if(!spanishName || !original.has(spanishName)) return;
    card.dataset.originalName=spanishName;
    const es=original.get(spanishName), en=EN[spanishName];
    if(toEnglish && en){
      card.querySelector('h2').textContent=en.name||spanishName;
      card.querySelector('.tag').textContent=CATEGORY_EN[es.category]||es.category;
      card.querySelector('.short').textContent=en.short;
      card.querySelector('.extended').textContent=en.extended;
      card.querySelector('details > summary').textContent=STATIC_EN.fiche;
      const cases=[...card.querySelectorAll('.case')]; en.cases.forEach((c,i)=>{if(!cases[i])return;cases[i].querySelector('b').textContent=c[0];cases[i].querySelector('span').textContent=c[1];cases[i].querySelector('.prompt').textContent=c[2];});
      [...card.querySelectorAll('.box:not(.limit) li')].forEach((li,i)=>{if(en.pros[i])li.textContent=en.pros[i];});
      [...card.querySelectorAll('.box.limit li')].forEach((li,i)=>{if(en.cons[i])li.textContent=en.cons[i];});
      const titles=card.querySelectorAll('.mini-title,.box h4'); if(titles[0])titles[0].textContent=STATIC_EN.useCases;if(titles[1])titles[1].textContent=STATIC_EN.advantages;if(titles[2])titles[2].textContent=STATIC_EN.limitations;
      const go=card.querySelector('a.primary'); if(go)go.textContent=STATIC_EN.go;
      card.dataset.text=[en.name||spanishName,CATEGORY_EN[es.category]||es.category,en.short,en.extended,en.cases.flat().join(' '),en.pros.join(' '),en.cons.join(' ')].join(' ').toLowerCase();
    }else{
      card.querySelector('h2').textContent=es.h2; card.querySelector('.tag').textContent=es.category; card.querySelector('.short').textContent=es.short; card.querySelector('.extended').textContent=es.extended; card.querySelector('details > summary').textContent=es.summary;
      const cases=[...card.querySelectorAll('.case')]; es.cases.forEach((c,i)=>{if(!cases[i])return;cases[i].querySelector('b').textContent=c.title;cases[i].querySelector('span').textContent=c.desc;cases[i].querySelector('.prompt').textContent=c.prompt;});
      [...card.querySelectorAll('.box:not(.limit) li')].forEach((li,i)=>{if(es.pros[i])li.textContent=es.pros[i];}); [...card.querySelectorAll('.box.limit li')].forEach((li,i)=>{if(es.cons[i])li.textContent=es.cons[i];});
      const titles=card.querySelectorAll('.mini-title,.box h4'); if(titles[0])titles[0].textContent='Casos de uso';if(titles[1])titles[1].textContent='✔ Ventajas';if(titles[2])titles[2].textContent='✘ Limitaciones'; const go=card.querySelector('a.primary');if(go)go.textContent='Ir a la herramienta ↗';
      card.dataset.text=[es.h2,es.category,es.short,es.extended,es.cases.map(c=>`${c.title} ${c.desc} ${c.prompt}`).join(' '),es.pros.join(' '),es.cons.join(' ')].join(' ').toLowerCase();
    }
  }

  function translateStatic(toEnglish){
    const h1=document.querySelector('header h1'), p=document.querySelector('header > p'), credit=document.querySelector('header .credit');
    const stats=[...document.querySelectorAll('.stat span')]; const search=document.getElementById('search');
    if(toEnglish){if(h1)h1.textContent=STATIC_EN.title;if(p)p.textContent=STATIC_EN.subtitle;if(credit)credit.textContent=STATIC_EN.credit;if(stats[0])stats[0].textContent=STATIC_EN.tools;if(stats[1])stats[1].textContent=STATIC_EN.categories;if(stats[2])stats[2].textContent=STATIC_EN.cases;if(search)search.placeholder=STATIC_EN.search;}
    else {if(h1)h1.textContent='Catálogo de Herramientas de IA para Educación';if(p)p.textContent='Repositorio editorial curado para identificar herramientas por uso pedagógico, no por tendencia tecnológica.';if(credit)credit.textContent='Curación realizada por Olaf Román ↗';if(stats[0])stats[0].textContent='Herramientas';if(stats[1])stats[1].textContent='Categorías';if(stats[2])stats[2].textContent='Casos con prompt';if(search)search.placeholder='Buscar...';}

    document.querySelectorAll('#categoryMenu details').forEach(d=>{const s=d.querySelector(':scope > summary');if(!s)return; const originalHtml=categoryOriginal.get(d);if(!originalHtml)return; if(toEnglish){const raw=s.textContent.replace(/\d+\s*$/,'').trim(); const esCat=Object.keys(CATEGORY_EN).find(k=>originalHtml.includes(k))||raw; const count=s.querySelector('small')?.textContent||''; s.innerHTML=`${CATEGORY_EN[esCat]||esCat} <small>${count}</small>`;}else{s.innerHTML=originalHtml;}});

    const note=document.querySelector('.note'); if(!note)return; const summary=note.querySelector(':scope > details > summary'); const blocks=[...note.querySelectorAll(':scope > details > div > div')];
    if(toEnglish){if(summary)summary.childNodes[0].textContent=STATIC_EN.guide+' '; if(blocks[0]){blocks[0].querySelector('h3').textContent=STATIC_EN.guideLeadTitle;blocks[0].querySelector('p').textContent=STATIC_EN.guideLead;} STATIC_EN.guideSections.forEach((sec,i)=>{const b=blocks[i+1];if(!b)return;b.querySelector('h3').textContent=sec[0];if(sec[1]&&b.querySelector('p'))b.querySelector('p').textContent=sec[1];}); const criteria=blocks[3]?.querySelectorAll('li');STATIC_EN.criteria.forEach((t,i)=>{if(criteria?.[i])criteria[i].textContent=t;}); const footer=blocks[8];if(footer)footer.childNodes[0].textContent=STATIC_EN.footer+' ';}
    else { location.reload(); }
  }

  function refreshResultCount(){
    const rc=document.getElementById('resultCount'), search=document.getElementById('search'); if(!rc||!search)return;
    const visible=[...document.querySelectorAll('.card')].filter(c=>!c.classList.contains('hidden')).length;
    if(currentLang==='en-US') rc.textContent=search.value.trim()?`${visible} result(s) for “${search.value}”`:`${document.querySelectorAll('.card').length} tools visible`;
  }

  function applyLanguage(){
    const en=currentLang==='en-US'; document.documentElement.lang=en?'en-US':'es-419';
    document.querySelectorAll('.card').forEach(c=>translateCard(c,en)); translateStatic(en); sortAlphabetically(); refreshResultCount();
  }

  function init(){
    snapshot(); addSelector(); sortAlphabetically();
    document.getElementById('search')?.addEventListener('input',()=>setTimeout(refreshResultCount,0));
    if(currentLang==='en-US') applyLanguage();
  }

  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init); else init();
})();
